cart-master/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'books#top'
  resources :books do
  resources :cart_items, only: [:index, :create, :update, :destroy]
 end
 delete :cart_items, to: 'cart_items#destroy_all'
end

cart-master/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

cart-master/app/models/book.rb
class Book < ApplicationRecord
	validates :title, presence: true
	validates :body, presence: true
end

cart-master/app/models/cart_item.rb
class CartItem < ApplicationRecord
end

cart-master/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

cart-master/app/controllers/books_controller.rb
class BooksController < ApplicationController
  def top
  end

  def index
  	@book = Book.new
  	@books = Book.all
  end

  def show
  	@book = Book.find(params[:id])
  end

  def new
  	@book = Book.new
  end

  def create
  	@book = Book.new(book_params)
  	if @book.save
      flash[:notice] = 'successfully'
      redirect_to book_path(@book.id)
    else
      @books = Book.all
      render 'index'
    end
  end

  def edit
  	@book = Book.find(params[:id])
  end

  def update
  	@book = Book.find(params[:id])
  	if @book.update(book_params)
      flash[:notice] = 'successfully'
  	  redirect_to book_path(@book.id)
    else
      @books = Book.all
      render 'index'
    end
  end

  def destroy
  	book = Book.find(params[:id])
  	book.destroy
  	redirect_to books_path
  end

  private
  def book_params
  	params.require(:book).permit(:title, :body)
  end


end

cart-master/app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
	def index
		@cart_items = CartItem.all
		@books = CartItem.all
	end

	def create
		@book = Book.find(params[:book_id])
		@cart_item = CartItem.new
		@cart_item.title = @book.title
		@cart_item.body = @book.body
		@cart_item.quantity = params[:quantity]
		@cart_item.save
		redirect_to book_cart_items_path
	end

	def destroy_all
		CartItem.destroy_all
		redirect_to root_path
	end

	def update
		@cart_item.update(quantity: params[:quantity].to_i)
        redirect_to book_cart_items_path
	end
end

cart-master/app/controllers/top_controller.rb
class TopController < ApplicationController
	def index
		
	end
end

cart-master/app/helpers/application_helper.rb
module ApplicationHelper
end

cart-master/app/helpers/books_helper.rb
module BooksHelper
end

cart-master/app/helpers/cart_items_helper.rb
module CartItemsHelper
end

cart-master/app/helpers/top_helper.rb
module TopHelper
end

cart-master/app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= form_for(@book) do |f| %>
    <h4>Title</h4>
    <%= f.text_field :title %>
    <h4>Body</h4>
    <%= f.text_area :body %>
    <%= f.submit 'Update Book' %>
<% end %>
<%= link_to 'Show', book_path(@book) %><%= '|' %><%= link_to 'Back', books_path(@book) %>

cart-master/app/views/books/index.html.erb
<h1>Books</h1>
  <table>
      <tr>
    	<th>Title</th>
    	<th>Body</th>
    	<th　class="method"></th>
      </tr>
    <% @books.each do |book| %>
      <tr>
      	<th><%= book.title %></th>
      	<th><%= book.body %></th>
      	<th><%= link_to "Show", book_path(book) %></th>
      	<th><%= link_to "Edit", edit_book_path(book) %></th>
      	<th><%= link_to "Destroy", book_path(book), method: :delete %></th>
        <th><%= form_tag(book_cart_items_path(book), method: :post) do %>
            <% book.title %><% book.body %>
            <%= select_tag 'quantity',options_for_select([['個数選択'],[1,1],[2,2],[3,3],[4,4],[5,5],[6,6],[7,7],[8,8],[9,9],[10,10]]) %>
            <input type="submit" value="add">
            <% end %>
        </th>
      </tr>
    <% end %>
  </table>
<%= form_for(@book) do |f| %>

   <h3 class="crearfix">New book</h3>
   <h4>Title</h4>
<% if @book.errors.any? %>
  <div id="error_explanation">
    <h2><%= @book.errors.count %>errors prohibited this book from being saved</h2>
    　<ul>
      　<% @book.errors.full_messages.each do |msg| %>
        　<li><%= msg %></li>
      　<% end %>
    　</ul>
  </div>
<% end %>
   <%= f.text_field :title %>

   <h4>Body</h4>
   <%= f.text_area :body %>

   <%= f.submit "Create Book" %>

<% end %>

cart-master/app/views/books/show.html.erb
<%= flash[:notice] %>
<p>Title:<%= @book.title %></p>
<p>Body:<%= @book.body %></p>

<%= link_to 'Edit', edit_book_path(@book) %><%= '|' %><%= link_to 'Back', books_path %>

cart-master/app/views/books/top.html.erb
<h1>ようこそBookersへ!</h1>
<p>Bookersでは、さまざまな書籍に関するあなたの意見や</p>
<p>印象を共有し交換することができます</p>
<%= link_to 'start', books_path %>

cart-master/app/views/cart_items/index.html.erb
    <h1>一覧</h1>
    <table>
      <% @cart_items.each do |book| %>
      <tr>
      	<th><%= book.title %></th>
      	<th><%= book.body %></th>
        <th><%= book.quantity %></th>
      </tr>
        <% end %>
        <%= button_to "全て削除", cart_items_path, method: :delete %>
      </table>

cart-master/app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

cart-master/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>